# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, null=True, verbose_name='User Name'),
        ),
    ]
