# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_recruiter',
            field=models.BooleanField(default=False, verbose_name='Is a Recruiter'),
        ),
    ]
