# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.PositiveIntegerField(verbose_name='Serial Number')),
                ('have_resume', models.BooleanField(default=False, verbose_name='Have Resume')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('mobile_no', models.CharField(max_length=20, verbose_name='Mobile Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('work_exp', models.PositiveIntegerField(default=0, verbose_name='Work Experience')),
                ('analytics_exp', models.PositiveIntegerField(default=0, verbose_name='Analytics Experience')),
                ('ctc', models.FloatField(default=0, verbose_name='Current CTC')),
                ('current_employer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Current Employer')),
                ('current_designation', models.CharField(blank=True, max_length=255, null=True)),
                ('current_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_city', to='core.City', verbose_name='Current city')),
                ('nearest_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nearest_city', to='core.City', verbose_name='Nearest City')),
                ('preferred_city', models.ManyToManyField(related_name='preferred_city', to='core.City', verbose_name='Preferred cities')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name_plural': 'Candidates',
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type', models.CharField(choices=[('PG_Course', 'PG_Course'), ('UG_Course', 'UG_Course'), ('Post_PG', 'Post_PG')], max_length=10, verbose_name='Course Type')),
                ('course_name', models.CharField(max_length=100, verbose_name='Course Name')),
                ('corrected_course_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Corrected Course Name')),
                ('institute', models.CharField(max_length=100, verbose_name='Institute')),
                ('tier1', models.BooleanField(default=False, verbose_name='Is Tier1')),
                ('passing_year', models.CharField(max_length=5, verbose_name='Passing Year')),
            ],
            options={
                'ordering': ('course_name',),
                'verbose_name_plural': 'Qualifications',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Skill')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='qualifications',
            field=models.ManyToManyField(to='candidate.Qualification', verbose_name='Qualifications'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='skills',
            field=models.ManyToManyField(to='candidate.Skill', verbose_name='Candidates Skillset'),
        ),
    ]
