# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 01:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='current_city',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_city', to='core.City', verbose_name='Current city'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='nearest_city',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='nearest_city', to='core.City', verbose_name='Nearest City'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='preferred_city',
            field=models.ManyToManyField(blank=True, related_name='preferred_city', to='core.City', verbose_name='Preferred cities'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='qualifications',
            field=models.ManyToManyField(blank=True, to='candidate.Qualification', verbose_name='Qualifications'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='skills',
            field=models.ManyToManyField(blank=True, to='candidate.Skill', verbose_name='Candidates Skillset'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='institute',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Institute'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='passing_year',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Passing Year'),
        ),
    ]
