# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 01:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_auto_20160528_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='current_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_city', to='core.City', verbose_name='Current city'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='nearest_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nearest_city', to='core.City', verbose_name='Nearest City'),
        ),
    ]
