# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_auto_20160528_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Skill'),
        ),
    ]
