# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 19:43
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidate', '0005_auto_20160528_0159'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadLimits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='qualification',
            name='course_type',
            field=models.CharField(choices=[('PG', 'PG_Course'), ('UG', 'UG_Course'), ('POST_PG', 'Post_PG')], max_length=10, verbose_name='Course Type'),
        ),
    ]
