# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0006_auto_20160528_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadlimits',
            name='counter',
        ),
    ]
