# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0007_remove_downloadlimits_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadlimits',
            name='num_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
